# Generated by Django 4.0.1 on 2022-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='excel_centry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=250)),
                ('numero_origen', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(max_length=250)),
                ('sku_producto', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'excel_centry',
                'verbose_name_plural': 'excel_centrys',
            },
        ),
        migrations.CreateModel(
            name='excel_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('rut', models.CharField(max_length=250)),
                ('razon_social', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'excel_factura',
                'verbose_name_plural': 'excel_facturas',
            },
        ),
    ]
