# Generated by Django 4.0.1 on 2022-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagen_jumpseller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku_imagen', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'imagen_jumpseller',
                'verbose_name_plural': 'imagen_jumpsellers',
            },
        ),
        migrations.CreateModel(
            name='imagen_mpn',
            fields=[
                ('imagen', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('cate', models.CharField(max_length=250)),
                ('marcas', models.CharField(max_length=250)),
                ('upc', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'imagen_mpn',
                'verbose_name_plural': 'imagen_mpns',
            },
        ),
        migrations.CreateModel(
            name='imagen_upc',
            fields=[
                ('image', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('cate', models.CharField(max_length=250)),
                ('marcas', models.CharField(max_length=250)),
                ('gti', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'imagen_upc',
                'verbose_name_plural': 'imagen_upcs',
            },
        ),
        migrations.CreateModel(
            name='imagenes',
            fields=[
                ('descripcion', models.CharField(max_length=250)),
                ('mpn', models.CharField(max_length=250)),
                ('centralrencno', models.CharField(max_length=250)),
                ('localSku', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('descricpcionfabrica', models.CharField(max_length=250)),
                ('descricpcionmarca', models.CharField(max_length=250)),
                ('categoriacompleta', models.CharField(max_length=250)),
                ('imagenes', models.CharField(max_length=250)),
                ('longitud', models.CharField(max_length=250)),
                ('altura', models.CharField(max_length=250)),
                ('anchura', models.CharField(max_length=250)),
                ('peso', models.CharField(max_length=250)),
                ('profundidad', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'imagene',
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('categoria', models.CharField(max_length=250)),
                ('precio', models.IntegerField()),
                ('marca', models.CharField(max_length=250)),
                ('mpn', models.CharField(max_length=250)),
                ('upc', models.CharField(max_length=250)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=7)),
                ('ancho', models.DecimalField(decimal_places=3, max_digits=7)),
                ('altura', models.DecimalField(decimal_places=3, max_digits=7)),
                ('largo', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
