# Generated by Django 4.0.1 on 2022-03-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntcomexApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes',
            old_name='descricpcionfabrica',
            new_name='descripcionfabrica',
        ),
        migrations.RenameField(
            model_name='imagenes',
            old_name='descricpcionmarca',
            new_name='descripcionmarca',
        ),
        migrations.AlterField(
            model_name='producto',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
